/**
 * Property-based tests for claim verification decision.
 *
 * **Validates: Requirements 9.3, 9.4**
 *
 * Properties:
 * 1. isClaimVerified(n) returns true for n ≥ 2
 * 2. isClaimVerified(n) returns false for n < 2
 * 3. correctCount is always between 0 and 3 (generated by verifyClaimAnswers)
 */
import { describe, it, expect } from 'vitest';
import * as fc from 'fast-check';
import { isClaimVerified, verifyClaimAnswers } from '@/lib/claimVerification';

describe('Property 13: Claim verification decision', () => {
  it('isClaimVerified(n) returns true for n ≥ 2', () => {
    fc.assert(
      fc.property(
        fc.integer({ min: 2, max: 100 }),
        (n) => {
          return isClaimVerified(n) === true;
        }
      ),
      { numRuns: 500 }
    );
  });

  it('isClaimVerified(n) returns false for n < 2', () => {
    fc.assert(
      fc.property(
        fc.integer({ min: -100, max: 1 }),
        (n) => {
          return isClaimVerified(n) === false;
        }
      ),
      { numRuns: 500 }
    );
  });

  it('correctCount from verifyClaimAnswers is always between 0 and 3', () => {
    // Generate arbitrary stored and submitted answer strings
    // The stored values need to be at least 3 chars to allow potential matches
    const storedArb = fc.record({
      name: fc.string({ minLength: 3, maxLength: 50 }),
      marking: fc.string({ minLength: 3, maxLength: 200 }),
      trait: fc.string({ minLength: 3, maxLength: 200 }),
    });

    const submittedArb = fc.record({
      name: fc.string({ minLength: 0, maxLength: 50 }),
      marking: fc.string({ minLength: 0, maxLength: 200 }),
      trait: fc.string({ minLength: 0, maxLength: 200 }),
    });

    fc.assert(
      fc.property(storedArb, submittedArb, (stored, submitted) => {
        const correctCount = verifyClaimAnswers(stored, submitted);
        return correctCount >= 0 && correctCount <= 3;
      }),
      { numRuns: 1000 }
    );
  });
});
